[tool.poetry]
name = "richardcampendotcom"
version = "0.1.0"
description = ""
authors = ["None"]

[tool.poetry.dependencies]
python = "^3.6"
Flask = "^1.1.2"
Flask-Script = "^2.0.6"
Flask-Sitemap = "^0.3.0"
psycopg2-binary = "^2.8.5"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
